#!/bin/bash

NAME="drf_hello_world"
DIR="/home/ftech/aniket/djangoprojects/drf_hello_world"
USER=ftech
GROUP=ftech
WORKERS=3
SOCKFILE="/run/gunicorn.sock"
DJANGO_SETTINGS_MODULE=drf_hello_world.settings
DJANGO_WSGI_MODULE=drf_hello_world.wsgi
LOG_LEVEL=debug
cd $DIR
source ./venv/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

#Command to run the progam under supervisor
exec ./venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $WORKERS \
--user=$USER \
--group=$GROUP \
--bind=unix:$SOCKFILE \
--log-level=$LOG_LEVEL \
--log-file=-
